export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
